correct conditions in CI-step for conda packaging and publishing (#830)
* run action on push for certain action
* unfreeze pytest-qt version

version 3.3.0 resulted in an exception:

>>> from pytestqt import logging
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jbq/.local/opt/mambaforge/envs/PyRS/lib/python3.8/site-packages/pytestqt/logging.py", line 5, in <module>
    from py._code.code import TerminalRepr, ReprFileLocation
ModuleNotFoundError: No module named 'py._code'; 'py' is not a package

See https://github.com/pylada/pylada-light/issues/55 for a discussion on the origin of this exception

* substitute deprecated np.float
* substitute deprecated np.int
* fuzzy constraining require pyqt version